#include "cdada/queue.h"
#include "cdada/__common_internal.h"
#include "cdada/__queue_internal.h"

#include <stdlib.h>
#include <string.h>

//DO NOT EDIT: Autogenerated with gen-srcs

using namespace std;

cdada_queue_t* __cdada_queue_create(const uint16_t val_size,
						__cdada_queue_ops_t* ops){

	__cdada_queue_int_t* m = NULL;

	if(unlikely(val_size == 0))
		return m;

	m = (__cdada_queue_int_t*)malloc(sizeof(__cdada_queue_int_t));
	memset(m, 0, sizeof(__cdada_queue_int_t));
	m->magic_num = CDADA_MAGIC;
	m->user_val_len = val_size;

	try{
		//Custom type
		if(ops){
			m->val_len = m->user_val_len = val_size;
			m->ops = ops;
			(*m->ops->create)(m);
			return m;
		}
{{ "" }}
		{%for t in types %}
			{%- if not loop.first -%}else {% endif -%}
			if(	{%- if t[2] < 3 -%}
					val_size == {{t[2]}}
				{%- else -%}
					val_size > {{ loop.previtem[2] }} && val_size <= {{ t[2] }}
				{%- endif -%}
			){
			m->queue.{{t[0]}} = new queue<{{t[1]}}>();
			m->val_len = {{t[2]}};
		}
		{%-endfor -%}
		else{
			goto ROLLBACK;
		}
	}catch(bad_alloc& e){
		goto ROLLBACK;
	}catch(...){
		CDADA_ASSERT(0);
		goto ROLLBACK;
	}

	return m;

ROLLBACK:
	free(m);
	return NULL;
}

/**
* Destroy a queue structure
*/
int cdada_queue_destroy(cdada_queue_t* queue){

	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;

	CDADA_CHECK_MAGIC(m);

	try{
		int c = m->ops? 0 : m->val_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				delete m->queue.{{t[0]}};
				break;
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				(*m->ops->destroy)(m);
				break;
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}
	}catch(...){
		CDADA_ASSERT(0);
		return CDADA_E_UNKNOWN;
	}

	m->magic_num = 0x0;
	free(m);

	return CDADA_SUCCESS;
}

int cdada_queue_push(cdada_queue_t* queue, const void* val){

	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;

	CDADA_CHECK_MAGIC(m);

	if(unlikely(!val))
		return CDADA_E_INVALID;

	if(m->max_capacity && cdada_queue_size(queue) >= m->max_capacity)
		return CDADA_E_FULL;

	try{
		int c = m->ops? 0 : m->val_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return cdada_queue_push_u<{{t[1]}}>(m,
								m->queue.{{t[0]}},
								val);
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				return (*m->ops->push)(m, val);
			default:
				break;
		}
	}catch(bad_alloc& e){
		return CDADA_E_MEM;
	}catch(...){}

	CDADA_ASSERT(0);
	return CDADA_E_UNKNOWN;
}

int cdada_queue_pop(cdada_queue_t* queue){

	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;

	CDADA_CHECK_MAGIC(m);

	try{
		int c = m->ops? 0 : m->val_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return cdada_queue_pop_u<{{t[1]}}>(m,
								m->queue.{{t[0]}});
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				return (*m->ops->pop)(m);
			default:
				break;
		}
	}catch(...){}

	CDADA_ASSERT(0);
	return CDADA_E_UNKNOWN;
}

uint32_t cdada_queue_size(const cdada_queue_t* queue){

	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;

	if(unlikely(!m || m->magic_num != CDADA_MAGIC))
		return 0;

	try{
		int c = m->ops? 0 : m->val_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return m->queue.{{t[0]}}->size();
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				return (*m->ops->size)(m);
			default:
				break;
		}
	}catch(...){}

	CDADA_ASSERT(0);
	return 0;
}

int cdada_queue_front(const cdada_queue_t* queue, void* val){

	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;

	CDADA_CHECK_MAGIC(m);

	if(unlikely(!val))
		return CDADA_E_INVALID;

	try{
		int c = m->ops? 0 : m->val_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return cdada_queue_front_u<{{t[1]}}>(m,
								m->queue.{{t[0]}},
								val);
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				return (*m->ops->front)(m, val);
			default:
				break;
		}
	}catch(bad_alloc& e){
		return CDADA_E_MEM;
	}catch(...){}

	CDADA_ASSERT(0);
	return CDADA_E_UNKNOWN;
}

int cdada_queue_back(const cdada_queue_t* queue, void* val){

	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;

	CDADA_CHECK_MAGIC(m);

	if(unlikely(!val))
		return CDADA_E_INVALID;

	try{
		int c = m->ops? 0 : m->val_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return cdada_queue_back_u<{{t[1]}}>(m,
								m->queue.{{t[0]}},
								val);
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				return (*m->ops->back)(m, val);
			default:
				break;
		}
	}catch(bad_alloc& e){
		return CDADA_E_MEM;
	}catch(...){}

	CDADA_ASSERT(0);
	return CDADA_E_UNKNOWN;
}

bool cdada_queue_empty(const cdada_queue_t* queue){

	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;

	if(unlikely(!m || m->magic_num != CDADA_MAGIC))
		return false;

	try{
		int c = m->ops? 0 : m->val_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return cdada_queue_empty_u<{{t[1]}}>(m,
								m->queue.{{t[0]}});
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				return (*m->ops->empty)(m);
			default:
				break;
		}
	}catch(...){}

	CDADA_ASSERT(0);
	return false;
}

uint64_t cdada_queue_get_max_capacity(const cdada_queue_t* queue){

	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;

	if(unlikely(!(m) || m->magic_num != CDADA_MAGIC))
		return 0;

	return m->max_capacity;
}

int cdada_queue_set_max_capacity(const cdada_queue_t* queue,
						const uint64_t limit){
	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;

	if(unlikely(!(m) || m->magic_num != CDADA_MAGIC))
		return CDADA_E_INVALID;

	m->max_capacity = limit;

	return CDADA_SUCCESS;
}

int cdada_queue_dump(cdada_queue_t* queue, uint32_t size, char* buffer,
							uint32_t* size_used){

	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;
	CDADA_CHECK_MAGIC(m);

	if(!size_used || (buffer&&size ==0))
		return CDADA_E_INVALID;

	try{
		std::stringstream ss;
		ss << "{";

		int c = m->ops? 0 : m->val_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				cdada_queue_dump_u<{{t[1]}}>(m,
								m->queue.{{t[0]}},
								ss);
				break;
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				(*m->ops->dump)(m, ss);
				break;
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}

		ss << "}";

		*size_used = ss.str().length()+1;
		if(!buffer)
			return CDADA_SUCCESS;

		snprintf(buffer, size, "%s", ss.str().c_str());
		if(ss.str().length()+1 > size)
			return CDADA_E_INCOMPLETE;
	}catch(bad_alloc& e){
		return CDADA_E_MEM;
	}catch(...){
		CDADA_ASSERT(0);
		return CDADA_E_UNKNOWN;
	}

	return CDADA_SUCCESS;
}

int cdada_queue_print(cdada_queue_t* queue, FILE *stream){

	__cdada_queue_int_t* m = (__cdada_queue_int_t*)queue;
	CDADA_CHECK_MAGIC(m);

	try{
		std::stringstream ss;
		ss << "{";

		int c = m->ops? 0 : m->val_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				cdada_queue_dump_u<{{t[1]}}>(m,
								m->queue.{{t[0]}},
								ss);
				break;
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				(*m->ops->dump)(m, ss);
				break;
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}
		ss << "}\n";

		fprintf(stream, "%s", ss.str().c_str());
	}catch(bad_alloc& e){
		return CDADA_E_MEM;
	}catch(...){
		CDADA_ASSERT(0);
		return CDADA_E_UNKNOWN;
	}

	return CDADA_SUCCESS;
}
