#include "cdada/set.h"
#include "cdada/__common_internal.h"
#include "cdada/__set_internal.h"

#include <stdlib.h>
#include <string.h>

//DO NOT EDIT: Autogenerated with gen-srcs

using namespace std;

cdada_set_t* __cdada_set_create(const uint16_t key_size,
						__cdada_set_ops_t* ops){

	__cdada_set_int_t* m = NULL;

	if(unlikely(key_size == 0))
		return m;

	m = (__cdada_set_int_t*)malloc(sizeof(__cdada_set_int_t));
	memset(m, 0, sizeof(__cdada_set_int_t));
	m->magic_num = CDADA_MAGIC;
	m->user_key_len = key_size;

	try{
		//Custom type
		if(ops){
			m->key_len = m->user_key_len = key_size;
			m->ops = ops;
			(*m->ops->create)(m);
			return m;
		}
{{ "" }}
		//Regular
		{%for t in types %}
			{%- if not loop.first -%}else {% endif -%}
			if(	{%- if t[2] < 3 -%}
					key_size == {{t[2]}}
				{%- else -%}
					key_size > {{ loop.previtem[2] }} && key_size <= {{ t[2] }}
				{%- endif -%}
			){
			m->set.{{t[0]}} = new set<{{t[1]}}>();
			m->key_len = {{t[2]}};
		}
		{%-endfor -%}
		else{
			//Unsupported; use custom type
			goto ROLLBACK;
		}
	}catch(bad_alloc& e){
		goto ROLLBACK;
	}catch(...){
		CDADA_ASSERT(0);
		goto ROLLBACK;
	}

	return m;

ROLLBACK:
	free(m);
	return NULL;
}

/**
* Destroy a set structure
*/
int cdada_set_destroy(cdada_set_t* set){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;

	CDADA_CHECK_MAGIC(m);

	try{
		if(m->ops){
			(*m->ops->destroy)(m);
		}else{
			switch(m->key_len){
			{%-for t in types %}
				case {{t[2]}}:
					delete m->set.{{t[0]}};
					break;
			{%-endfor %}
				default:
					CDADA_ASSERT(0);
					break;
			}
		}
	}catch(...){
		CDADA_ASSERT(0);
		return CDADA_E_UNKNOWN;
	}

	m->magic_num = 0x0;
	free(m);

	return CDADA_SUCCESS;
}

int cdada_set_clear(cdada_set_t* set){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;

	CDADA_CHECK_MAGIC(m);

	try{
		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				m->set.{{t[0]}}->clear();
				break;
		{%-endfor %}
			case 0:
				(*m->ops->clear)(m);
				break;
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}
	}catch(bad_alloc& e){
		return CDADA_E_MEM;
	}catch(...){
		CDADA_ASSERT(0);
		return CDADA_E_UNKNOWN;
	}

	return CDADA_SUCCESS;
}

bool cdada_set_empty(const cdada_set_t* set){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;

	if(unlikely(!m || m->magic_num != CDADA_MAGIC))
		return false;

	try{
		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return m->set.{{t[0]}}->empty();
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				return (*m->ops->empty)(m);
			default:
				CDADA_ASSERT(0);
				return false;
		}
	}catch(...){
		CDADA_ASSERT(0);
		return false;
	}

	return false;
}

uint32_t cdada_set_size(const cdada_set_t* set){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;

	if(unlikely(!m || m->magic_num != CDADA_MAGIC))
		return 0;

	try{
		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return m->set.{{t[0]}}->size();
		{%-endfor %}
			case 0:
				return (*m->ops->size)(m);
			default:
				CDADA_ASSERT(0);
				break;
		}
	}catch(...){
		CDADA_ASSERT(0);
		return 0;
	}

	return 0;
}

int cdada_set_insert(cdada_set_t* set, const void* key){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;

	CDADA_CHECK_MAGIC(m);

	if(unlikely(!key))
		return CDADA_E_INVALID;

	//NOTE: we don't want std::set insert "replace semantics", so we return
	//E_EXISTS if key is present in the set
	try{
		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return cdada_set_insert_u<{{t[1]}}>(m,
								m->set.{{t[0]}},
								key);
		{%-endfor %}
			case 0:
				return (*m->ops->insert)(m, key);
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}
	}catch(bad_alloc& e){
		return CDADA_E_MEM;
	}catch(...){}

	CDADA_ASSERT(0);
	return CDADA_E_UNKNOWN;
}

int cdada_set_erase(cdada_set_t* set, const void* key){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;

	CDADA_CHECK_MAGIC(m);

	if(unlikely(!key))
		return CDADA_E_INVALID;

	try{
		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return cdada_set_erase_u<{{t[1]}}>(m,
								m->set.{{t[0]}},
								key);
		{%-endfor %}
			case 0:
				return (*m->ops->erase)(m, key);
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}
	}catch(bad_alloc& e){
		return CDADA_E_MEM;
	}catch(...){}

	CDADA_ASSERT(0);
	return CDADA_E_UNKNOWN;
}

bool cdada_set_find(const cdada_set_t* set, const void* key){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;

	if(unlikely(!m || m->magic_num != CDADA_MAGIC || !key))
		return false;

	try{
		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return cdada_set_find_u<{{t[1]}}>(m,
								m->set.{{t[0]}},
								key);
		{%-endfor %}
			case 0:
				return (*m->ops->find)(m, key);
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}
	}catch(...){}

	CDADA_ASSERT(0);
	return false;
}

static int __cdada_set_first_last(const cdada_set_t* set, bool first,
								void* key){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;

	if(unlikely(!m || m->magic_num != CDADA_MAGIC || !key))
		return false;

	try{
		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				return cdada_set_first_last_u<{{t[1]}}>(m,
								m->set.{{t[0]}},
								first, key);
		{%-endfor %}
			case 0:
				return (*m->ops->first_last)(m, first, key);
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}
	}catch(...){}

	CDADA_ASSERT(0);
	return false;
}

int cdada_set_first(const cdada_set_t* set, void* key){
	return __cdada_set_first_last(set, true, key);
}

int cdada_set_last(const cdada_set_t* set, void* key){
	return __cdada_set_first_last(set, false, key);
}

int cdada_set_traverse(const cdada_set_t* set, cdada_set_it f, void* opaque){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;

	CDADA_CHECK_MAGIC(m);

	if(unlikely(!f))
		return CDADA_E_INVALID;

	try{
		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				cdada_set_traverse_u<{{t[1]}}>(m,
								m->set.{{t[0]}},
								f,
								opaque);
				break;
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				(*m->ops->traverse)(m, f, opaque);
				break;
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}
	}catch(...){
		CDADA_ASSERT(0);
		return CDADA_E_UNKNOWN;
	}

	return CDADA_SUCCESS;
}

int cdada_set_rtraverse(const cdada_set_t* set, cdada_set_it f, void* opaque){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;

	CDADA_CHECK_MAGIC(m);

	if(unlikely(!f))
		return CDADA_E_INVALID;

	try{
		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				cdada_set_rtraverse_u<{{t[1]}}>(m,
								m->set.{{t[0]}},
								f,
								opaque);
				break;
		{%-endfor %}
			case 0:
				(*m->ops->rtraverse)(m, f, opaque);
				break;
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}
	}catch(...){
		CDADA_ASSERT(0);
		return CDADA_E_UNKNOWN;
	}

	return CDADA_SUCCESS;
}

int cdada_set_dump(cdada_set_t* set, uint32_t size, char* buffer,
							uint32_t* size_used){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;
	CDADA_CHECK_MAGIC(m);

	if(!size_used || (buffer&&size ==0))
		return CDADA_E_INVALID;

	try{
		std::stringstream ss;
		ss << "{";

		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				cdada_set_dump_u<{{t[1]}}>(m, m->set.{{t[0]}},
								ss);
				break;
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				(*m->ops->dump)(m, ss);
				break;
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}

		ss << "}";

		*size_used = ss.str().length()+1;
		if(!buffer)
			return CDADA_SUCCESS;

		snprintf(buffer, size, "%s", ss.str().c_str());
		if(ss.str().length()+1 > size)
			return CDADA_E_INCOMPLETE;
	}catch(bad_alloc& e){
		return CDADA_E_MEM;
	}catch(...){
		CDADA_ASSERT(0);
		return CDADA_E_UNKNOWN;
	}

	return CDADA_SUCCESS;
}

int cdada_set_print(cdada_set_t* set, FILE *stream){

	__cdada_set_int_t* m = (__cdada_set_int_t*)set;
	CDADA_CHECK_MAGIC(m);

	try{
		std::stringstream ss;
		ss << "{";

		int c = m->ops? 0 : m->key_len;
		switch(c){
		{%-for t in types %}
			case {{t[2]}}:
				cdada_set_dump_u<{{t[1]}}>(m, m->set.{{t[0]}},
								ss);
				break;
		{%-endfor %}
			case 0:
				CDADA_ASSERT(m->ops);
				(*m->ops->dump)(m, ss);
				break;
			default:
				CDADA_ASSERT(0);
				return CDADA_E_UNKNOWN;
		}
		ss << "}\n";

		fprintf(stream, "%s", ss.str().c_str());
	}catch(bad_alloc& e){
		return CDADA_E_MEM;
	}catch(...){
		CDADA_ASSERT(0);
		return CDADA_E_UNKNOWN;
	}

	return CDADA_SUCCESS;
}
